"""init

Revision ID: 08520e9c1b7b
Revises:
Create Date: 2023-06-25 00:23:18.202353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "08520e9c1b7b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "DISTANCE_TRAVELLED",
                "TIME_SPENT",
                "CALORIES_BURNED",
                "TARGETS_COMPLETED",
                name="targettype",
            ),
            nullable=False,
        ),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Float(precision=9), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reports_id"), ["id"], unique=False
        )

    op.create_table(
        "targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "DISTANCE_TRAVELLED",
                "TIME_SPENT",
                "CALORIES_BURNED",
                "TARGETS_COMPLETED",
                name="targettype",
            ),
            nullable=False,
        ),
        sa.Column("limit", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current", sa.Float(precision=9), nullable=False),
        sa.Column("target", sa.Float(precision=9), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("targets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_targets_id"), ["id"], unique=False
        )

    op.create_table(
        "target_multimedias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("target_multimedias", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_target_multimedias_id"), ["id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("target_multimedias", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_target_multimedias_id"))

    op.drop_table("target_multimedias")
    with op.batch_alter_table("targets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_targets_id"))

    op.drop_table("targets")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_id"))

    op.drop_table("reports")
    # ### end Alembic commands ###

    # https://github.com/sqlalchemy/alembic/issues/278
    target_type_enum = sa.Enum(
        "DISTANCE_TRAVELLED",
        "TIME_SPENT",
        "CALORIES_BURNED",
        "TARGETS_COMPLETED",
        name="targettype",
    )
    target_type_enum.drop(op.get_bind())  # type: ignore
