"""init

Revision ID: 33ed8ee531d0
Revises:
Create Date: 2023-06-18 20:46:38.057148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "33ed8ee531d0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("limit", sa.Integer(), nullable=False),
        sa.Column("current", sa.Float(precision=9), nullable=False),
        sa.Column("target", sa.Float(precision=9), nullable=False),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("targets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_targets_id"), ["id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("targets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_targets_id"))

    op.drop_table("targets")
    # ### end Alembic commands ###
