"""add reports

Revision ID: 9c7d02ad40e2
Revises: 93ce878ad451
Create Date: 2023-06-24 21:19:09.823886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c7d02ad40e2"
down_revision = "93ce878ad451"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "DISTANCE_TRAVELLED",
                "TIME_SPENT",
                "CALORIES_BURNED",
                "TARGETS_COMPLETED",
                name="targettype",
            ),
            nullable=False,
        ),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("count", sa.Float(precision=9), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reports_id"), ["id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_id"))

    op.drop_table("reports")
    # ### end Alembic commands ###
